# -*- coding: utf-8 -*-
"""Copy of Uber_Ride_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rx_vjxMzXkWLbFr8erMQ1OQcdeO_WvLL

# Uber Ride Analysis

## Project Overview

This project performs Exploratory Data Analysis (EDA) on an Uber ride dataset using Python. The analysis focuses on understanding ride patterns, ride duration, travel distance, weekdays, monthly trends, round trips, and other useful insights through data preprocessing and visualization.

### Tools Used

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- Scikit-learn

### Objectives

- Load and understand the dataset
- Clean and preprocess the data
- Create useful features
- Perform Exploratory Data Analysis (EDA)
- Visualize important ride trends
- Apply Scaling and Encoding
- Extract meaningful business insights
"""

# ============================
# Import Required Libraries
# ============================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings("ignore")

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("uber_rides_dataset.csv")

print("Dataset Loaded Successfully!")

df.head()

# Display the last 5 rows
df.tail()

# Number of rows and columns
df.shape

# Total number of values
df.size

# Dataset information
df.info()

# Display all column names
df.columns

# Data types of each column
df.dtypes

# Display 5 random rows
df.sample(5)

# Display current column names
df.columns

# Remove '*' from column names
df.columns = df.columns.str.replace('*', '', regex=False)

# Display updated column names
df.columns

# Check for missing values
df.isnull()

# Count missing values in each column
df.isnull().sum()

# Fill missing values in PURPOSE with the most frequent value
df["PURPOSE"] = df["PURPOSE"].fillna(df["PURPOSE"].mode()[0])

# Check again
df.isnull().sum()

# Average miles by category
df.groupby("CATEGORY")["MILES"].mean()

# Average miles for each category
df["AVG_CATEGORY_MILES"] = df.groupby("CATEGORY")["MILES"].transform("mean")

df.head()

# Categories with more than 100 rides
df.groupby("CATEGORY").filter(lambda x: len(x) > 100)

# Count rides by category
df["CATEGORY"].value_counts()

# Check duplicate rows
df.duplicated()

# Count duplicate rows
df.duplicated().sum()

# Display duplicate rows
df[df.duplicated()]

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Check duplicates again
df.duplicated().sum()

# Summary statistics for numerical columns
df.describe()

# Summary statistics for categorical columns
df.describe(include='object')

# Summary statistics for all columns
df.describe(include='all')

# ==========================================================
# Convert START_DATE and END_DATE to Datetime
# ==========================================================

df["START_DATE"] = pd.to_datetime(df["START_DATE"])
df["END_DATE"] = pd.to_datetime(df["END_DATE"])

# Check updated data types
df.dtypes

# Create Date column
df["date"] = df["START_DATE"].dt.date

df[["START_DATE","date"]].head()

# Create Time column
df["time"] = df["START_DATE"].dt.strftime("%H:%M")

df[["START_DATE","time"]].head()

# Create Day/Night column
df["day_night"] = np.where(
    (df["START_DATE"].dt.hour >= 6) &
    (df["START_DATE"].dt.hour < 18),
    "Day",
    "Night"
)

df[["START_DATE","day_night"]].head()

# Create Round Trip column
df["ROUND_TRIP"] = np.where(
    df["START"] == df["STOP"],
    "Yes",
    "No"
)

df[["START","STOP","ROUND_TRIP"]].head()

# Create Month column
df["MONTH"] = df["START_DATE"].dt.month_name()

df[["START_DATE","MONTH"]].head()

# Ride duration in minutes
df["MINUTES"] = (
    df["END_DATE"] - df["START_DATE"]
).dt.total_seconds() / 60

df[["START_DATE","END_DATE","MINUTES"]].head()

# Create Weekday column
df["WEEKDAY"] = df["START_DATE"].dt.day_name()

df[["START_DATE","WEEKDAY"]].head()

# Create Ride Duration column
df["RIDE_DURATION"] = df["MINUTES"]

df[["MINUTES","RIDE_DURATION"]].head()

# Start time of the next ride
df["NEXT_RIDE"] = df["START_DATE"].shift(-1)

df[["START_DATE","NEXT_RIDE"]].head()

# Time gap between rides (minutes)
df["TIME_DIFF"] = (
    df["NEXT_RIDE"] - df["END_DATE"]
).dt.total_seconds() / 60

df[["END_DATE","NEXT_RIDE","TIME_DIFF"]].head()

# Display all column names
df.columns

# ==========================================================
# Boxplot for MILES
# ==========================================================

plt.figure(figsize=(8,5))

sns.boxplot(x=df["MILES"])

plt.title("Boxplot of Ride Distance (MILES)")
plt.xlabel("Miles")

plt.show()

# ==========================================================
# Calculate IQR
# ==========================================================

Q1 = df["MILES"].quantile(0.25)

Q3 = df["MILES"].quantile(0.75)

IQR = Q3 - Q1

print("Q1 :", Q1)
print("Q3 :", Q3)
print("IQR:", IQR)

# ==========================================================
# Lower and Upper Limits
# ==========================================================

lower_limit = Q1 - 1.5 * IQR

upper_limit = Q3 + 1.5 * IQR

print("Lower Limit :", lower_limit)
print("Upper Limit :", upper_limit)

# ==========================================================
# Display Outliers
# ==========================================================

outliers = df[(df["MILES"] < lower_limit) | (df["MILES"] > upper_limit)]

outliers

# ==========================================================
# Count Outliers
# ==========================================================

print("Number of Outliers :", outliers.shape[0])

# ==========================================================
# Remove Outliers
# ==========================================================

df = df[(df["MILES"] >= lower_limit) &
        (df["MILES"] <= upper_limit)]

df.shape

# ==========================================================
# Boxplot After Removing Outliers
# ==========================================================

plt.figure(figsize=(8,5))

sns.boxplot(x=df["MILES"])

plt.title("Boxplot After Removing Outliers")

plt.show()

# ==========================================================
# Cap Outliers using np.where()
# ==========================================================

df["MILES"] = np.where(
    df["MILES"] > upper_limit,
    upper_limit,
    df["MILES"]
)

# ==========================================================
# Histogram - Ride Distance
# ==========================================================

plt.figure(figsize=(8,5))

sns.histplot(df["MILES"], bins=30, kde=True, color="skyblue")

plt.title("Distribution of Ride Distance")
plt.xlabel("Miles")
plt.ylabel("Frequency")

plt.show()

# ==========================================================
# Distribution Plot - Ride Duration
# ==========================================================

sns.displot(
    df["RIDE_DURATION"],
    bins=30,
    kde=True,
    height=5,
    aspect=1.5
)

plt.show()

# ==========================================================
# Count Plot - Ride Category
# ==========================================================

plt.figure(figsize=(6,5))

sns.countplot(x="CATEGORY", data=df)

plt.title("Number of Rides by Category")
plt.xlabel("Category")
plt.ylabel("Count")

plt.show()

# ==========================================================
# Count Plot - Weekday
# ==========================================================

plt.figure(figsize=(10,5))

sns.countplot(
    x="WEEKDAY",
    data=df,
    order=[
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday",
        "Saturday",
        "Sunday"
    ]
)

plt.title("Rides by Weekday")
plt.xlabel("Weekday")
plt.ylabel("Number of Rides")

plt.xticks(rotation=45)

plt.show()

# ==========================================================
# Count Plot - Month
# ==========================================================

plt.figure(figsize=(12,5))

sns.countplot(
    x="MONTH",
    data=df,
    order=[
        "January","February","March","April","May","June",
        "July","August","September","October","November","December"
    ]
)

plt.title("Monthly Uber Rides")
plt.xlabel("Month")
plt.ylabel("Count")

plt.xticks(rotation=45)

plt.show()

# ==========================================================
# Count Plot - Day/Night
# ==========================================================

plt.figure(figsize=(5,5))

sns.countplot(x="day_night", data=df)

plt.title("Day vs Night Rides")
plt.xlabel("Ride Time")
plt.ylabel("Count")

plt.show()

# ==========================================================
# Pie Chart - Ride Category
# ==========================================================

plt.figure(figsize=(6,6))

df["CATEGORY"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%",
    startangle=90
)

plt.title("Ride Category Distribution")

plt.ylabel("")

plt.show()

# ==========================================================
# Bar Plot - Average Miles
# ==========================================================

plt.figure(figsize=(6,5))

sns.barplot(
    x="CATEGORY",
    y="MILES",
    data=df
)

plt.title("Average Ride Distance by Category")
plt.xlabel("Category")
plt.ylabel("Average Miles")

plt.show()

# ==========================================================
# Box Plot - Ride Distance
# ==========================================================

plt.figure(figsize=(8,5))

sns.boxplot(x=df["MILES"])

plt.title("Ride Distance Distribution")

plt.show()

# ==========================================================
# Scatter Plot - Ride Duration vs Miles
# ==========================================================

plt.figure(figsize=(8,5))

sns.scatterplot(
    x="RIDE_DURATION",
    y="MILES",
    data=df
)

plt.title("Ride Duration vs Ride Distance")
plt.xlabel("Ride Duration (Minutes)")
plt.ylabel("Distance (Miles)")

plt.show()

# ==========================================================
# Regression Plot
# ==========================================================

plt.figure(figsize=(8,5))

sns.regplot(
    x="RIDE_DURATION",
    y="MILES",
    data=df,
    scatter_kws={"alpha":0.5},
    line_kws={"color":"red"}
)

plt.title("Ride Duration vs Miles (Regression Line)")
plt.xlabel("Ride Duration (Minutes)")
plt.ylabel("Distance (Miles)")

plt.show()

# ==========================================================
# Pair Plot
# ==========================================================

sns.pairplot(
    df[
        [
            "MILES",
            "MINUTES",
            "RIDE_DURATION",
            "TIME_DIFF"
        ]
    ]
)

plt.show()

# ==========================================================
# FacetGrid
# ==========================================================

g = sns.FacetGrid(
    df,
    col="CATEGORY",
    height=5
)

g.map(
    sns.histplot,
    "MILES"
)

plt.show()

# ==========================================================
# Minutes vs Time Difference
# ==========================================================

plt.figure(figsize=(8,5))

sns.scatterplot(
    x="MINUTES",
    y="TIME_DIFF",
    data=df
)

plt.title("Ride Minutes vs Time Gap to Next Ride")
plt.xlabel("Ride Duration (Minutes)")
plt.ylabel("Time Difference (Minutes)")

plt.show()

# ==========================================================
# Category vs Miles
# ==========================================================

plt.figure(figsize=(8,5))

sns.boxplot(
    x="CATEGORY",
    y="MILES",
    data=df
)

plt.title("Ride Distance by Category")

plt.show()

# ==========================================================
# Weekday vs Ride Duration
# ==========================================================

plt.figure(figsize=(12,5))

sns.violinplot(
    x="WEEKDAY",
    y="RIDE_DURATION",
    data=df,
    order=[
        "Monday","Tuesday","Wednesday",
        "Thursday","Friday","Saturday","Sunday"
    ]
)

plt.xticks(rotation=45)

plt.title("Ride Duration Across Weekdays")

plt.show()

# ==========================================================
# Heatmap
# ==========================================================

plt.figure(figsize=(8,6))

numeric_df = df.select_dtypes(include=np.number)

sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap="viridis",
    fmt=".2f"
)

plt.title("Correlation Heatmap")

plt.show()

# ==========================================================
# Swarm Plot
# ==========================================================

plt.figure(figsize=(8,5))

sns.swarmplot(
    x="CATEGORY",
    y="MILES",
    data=df
)

plt.title("Ride Distance by Category")

plt.show()

# ==========================================================
# Strip Plot
# ==========================================================

plt.figure(figsize=(8,5))

sns.stripplot(
    x="CATEGORY",
    y="MILES",
    data=df,
    jitter=True,
    alpha=0.5
)

plt.title("Ride Distance by Category")

plt.show()

# ==========================================================
# Violin Plot
# ==========================================================

plt.figure(figsize=(8,5))

sns.violinplot(
    x="day_night",
    y="RIDE_DURATION",
    data=df
)

plt.title("Ride Duration - Day vs Night")

plt.show()

# ==========================================================
# Line Plot
# ==========================================================

monthly = df.groupby("MONTH")["RIDE_DURATION"].mean().reset_index()

month_order = [
    "January","February","March","April","May","June",
    "July","August","September","October","November","December"
]

monthly["MONTH"] = pd.Categorical(
    monthly["MONTH"],
    categories=month_order,
    ordered=True
)

monthly = monthly.sort_values("MONTH")

plt.figure(figsize=(12,5))

sns.lineplot(
    x="MONTH",
    y="RIDE_DURATION",
    data=monthly,
    marker="o"
)

plt.xticks(rotation=45)

plt.title("Average Ride Duration by Month")

plt.show()

# ==========================================================
# Bar Plot
# ==========================================================

weekday = df.groupby("WEEKDAY")["RIDE_DURATION"].mean().reset_index()

weekday_order = [
    "Monday","Tuesday","Wednesday",
    "Thursday","Friday","Saturday","Sunday"
]

weekday["WEEKDAY"] = pd.Categorical(
    weekday["WEEKDAY"],
    categories=weekday_order,
    ordered=True
)

weekday = weekday.sort_values("WEEKDAY")

plt.figure(figsize=(10,5))

sns.barplot(
    x="WEEKDAY",
    y="RIDE_DURATION",
    data=weekday
)

plt.xticks(rotation=45)

plt.title("Average Ride Duration by Weekday")

plt.show()

# ==========================================================
# Pie Chart
# ==========================================================

plt.figure(figsize=(6,6))

df["day_night"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%",
    startangle=90
)

plt.title("Day vs Night Ride Distribution")

plt.ylabel("")

plt.show()

# ==========================================================
# Count Plot
# ==========================================================

plt.figure(figsize=(6,5))

sns.countplot(
    x="ROUND_TRIP",
    data=df
)

plt.title("Round Trip Distribution")

plt.show()

# ==========================================================
# Scatter Plot
# ==========================================================

plt.figure(figsize=(8,5))

sns.scatterplot(
    x="MILES",
    y="TIME_DIFF",
    data=df
)

plt.title("Miles vs Time Difference")

plt.show()

# ==========================================================
# Select Numerical Columns
# ==========================================================

df.select_dtypes(include=np.number).head()

from sklearn.preprocessing import StandardScaler

# Create StandardScaler object
scaler = StandardScaler()

# ==========================================================
# Apply Standard Scaling
# ==========================================================

columns_to_scale = [
    "MILES",
    "MINUTES",
    "RIDE_DURATION",
    "TIME_DIFF"
]

df[columns_to_scale] = scaler.fit_transform(df[columns_to_scale])

df.head()

df.describe()

# ==========================================================
# Categorical Columns
# ==========================================================

df.select_dtypes(include="object").columns

# ==========================================================
# Label Encoding
# ==========================================================

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

df["CATEGORY"] = label_encoder.fit_transform(df["CATEGORY"])

df["day_night"] = label_encoder.fit_transform(df["day_night"])

df["ROUND_TRIP"] = label_encoder.fit_transform(df["ROUND_TRIP"])

df.head()

df[["CATEGORY","day_night","ROUND_TRIP"]].head()

# ==========================================================
# One-Hot Encoding
# ==========================================================

df = pd.get_dummies(
    df,
    columns=[
        "MONTH",
        "WEEKDAY",
        "PURPOSE"
    ]
)

df.head()

df.info()

# ==========================================================
# Save Processed Dataset
# ==========================================================

df.to_csv("uber_rides_processed.csv", index=False)

print("Processed dataset saved successfully!")